from app.controllers.farmer_controller import farmer_bp
from app.controllers.dairy_owner_controller import dairy
from app.controllers.farmer_bank_controller import bank
from app.controllers.muster_controller import muster_
from app.controllers.supplies_controller import supplies
from app.controllers.supplies_transaction_controller import supply_transaction